spring.application.name=Project2

spring.datasource.url=${Database_URL}
spring.datasource.username=${DB_username}
spring.datasource.password=${DB_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT Properties
jwt.secret=${JWT_secret}
jwt.expiration=${JWT_expiration}
server.port = ${PORT}